language: python
matrix:
  include:
  - python: '3.7'
  - python: '3.8'
  - python: '3.9'
  - python: '3.10'
  - python: '3.11'
  fast_finish: true
dist: xenial
sudo: true
install:
- pip install coverage
- pip install coveralls
- pip install -e .
script:
- coverage run --source=pyernluefter setup.py test
after_success:
- coverage report
- coveralls
deploy:
  provider: pypi
  on:
    branch: master
    python: '3.11'
  skip_existing: true
  user: "__token__"
  password:
    secure: FlFBkrHAgyL+ih1MVrgQ8ZuI6olhiL3TqL0o1plOHj9ooqlib5CTZ6C+pfeqVFRSkVnYMNMT4R7f7foTzhK/gJdaZS39sePlqmumZgKqOayyYCGlXfdLD7CVRwsUmpO9VLCViAx5lvIhjcbcdxlL+xgYXstSYnVqUxuXjeOBNOeo8rQd+iqpvUfABaWbbDZrB1S74+aS8BVhzKIXRXR4OgPbB44B68Dmy2JN2inp00BAT8f+afneviDyvTi2XdhebZOgP56dCOPCSPcH86xqxw4ddym5jX+NcvghuovEWv9/yMPpvpxqBumZu0B/NGIWjFkw8v0q2KnsIUXZHveku67XVFVkrz4c11BnbX8gQQQiE2GhD6ctA5wZDgB0yk97jSfRyLiIy6u8617OqOMUktFP/IyZJ/TnCox+QjZKN7n6LrmF+W177DNkiU2bpHKbHZVqpcVcyhatL0JowGZ3XMdyl/b7Yq8PZztA8LTHY56KHb0gCPhC13Lc/KveL0nltJJ2zCO+YrykTLSFhfvHwwkkx/W1RIjka29tLSUOyn1GeSF+FvJQ7Sm/TCLY1KLU3zvDgiTmuZpDSgNkXsjnhQfLzW7xm+V5ZcSsy6Z+JM9jwkyGAmfJUYNj1sY3+IdSwZpYFCkU0d0OxzbhVr/lgV3/hqOH1C1YpF4DyPzCTtM=
